### ISSUE TITLE
Set text width limit

### ISSUE THREAD

**Issue by nobe4** [nobe4/ElevATC#12]
![screen shot 2014-12-29 at 18 08 40](https://cloud.githubusercontent.com/assets/2452791/5570669/c71e06e6-8f85-11e4-8318-82b97f408c0b.png)

**Comment by npny** [comment]
In this particular case, it's caused by "Staunton/Waynesboro/Harrisonburg" being considered a single continuous word by the css text flow layout engine. Changing to `word-wrap: break-word;` on the `.infoList` container works, but then the line can be split anywhere in the middle of this giant string. The only other solution is to insert [wbr](http://www.w3schools.com/tags/tag_wbr.asp) tags around the '/' characters. The line is then split at the correct location, while still maintaining the same visual appearance. This means we have to modify the string before it is inserted in javascript.
